Add service generator
swarmion/template pull request #102
Opened 2022-03-11 16:46 UTC by guillaumeduboc

2022-03-11 17:00 UTC, fargito commented on tools/generators/service/index.ts
> +/* eslint-disable max-lines */
Tu peux enlever ça je pense

2022-03-11 17:02 UTC, fargito commented on tools/generators/service/typed-json-config/package.json.ts
> +    '@types/http-errors': '^1.8.2',
Is this necessary?

2022-03-11 17:16 UTC, fargito commented
Do you think there would be a way to replace `@swarmion-starter/` from the tmpl files, for example by using the `npmScope` from nx?

2022-03-12 18:07 UTC, guillaumeduboc commented on tools/generators/service/typed-json-config/package.json.ts
> +    'http-errors': '^2.0.0',
I removed them as in `backend/core`

2022-03-12 18:08 UTC, guillaumeduboc commented on tools/generators/service/typed-json-config/package.json.ts
> +    '@types/http-errors': '^1.8.2',
I removed them as in `backend/core`

2022-03-12 18:08 UTC, guillaumeduboc commented
> Do you think there would be a way to replace `@swarmion-starter/` from the tmpl files, for example by using the `npmScope` from nx?

I replaced all occurence of `@swarmion-starter/` in our templated files 😃

2022-03-14 08:07 UTC, adriencaccia requested changes

2022-03-14 08:07 UTC, adriencaccia commented on tools/generators/service/typed-json-config/tsconfig.json.ts
> +    { path: '../../packages/serverless-helpers' },
As we have seen, we need to point to a different config.
```suggestion
    { path: '../../packages/serverless-helpers/tsconfig.build.json' },
```
Could also make the change in `backend/core/tsconfig.json`, in a different commit ?

2022-03-16 09:42 UTC, fargito approved these changes
Great job! Thanks a lot :tada:

2022-03-18 14:35 UTC, adriencaccia commented
`eslint` is not working

![image](https://user-images.githubusercontent.com/19605940/159022855-c50d7e2c-cc82-4fc7-8c96-01058bc74c84.png)

2022-03-18 14:36 UTC, adriencaccia commented
The `.vscode` symlinked folder is using absolute paths, we need to change it to relative paths
![image](https://user-images.githubusercontent.com/19605940/159022993-b9b896bc-ab88-4d39-ba86-12b9ef983f01.png)

2022-03-18 14:42 UTC, guillaumeduboc commented
> `eslint` is not working
> 
> ![image](https://user-images.githubusercontent.com/19605940/159022855-c50d7e2c-cc82-4fc7-8c96-01058bc74c84.png)

indeed, eslint is not in the dependencies

2022-03-18 16:16 UTC, adriencaccia approved these changes

2022-03-18 16:19 UTC, merged